### ISSUE TITLE
{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

### ISSUE THREAD

**Issue by squall2751** [lequal/sonar-cnes-report#117]
Hi, I got some error when using cnes-report plugin on sonarqube v6.7.1.

### Steps to reproduce behavior
1. Click the cnes-report on sonarqube server
2. Choose the project and click generate 

### Detection version
SonarQube Server Version 6.7.1
CNES-Report 3.0 and 2.X

###Error Log
2020.03.06 10:41:24 ERROR web[AXCttw7YwGNpp6rgAABP][o.s.s.w.WebServiceEngine] Fail to process request http://webserver:9000/api/cnesreport/report?key=Report%3AService&author=Administrator&token=7fb95af262e18759b2ee9e8817617a9a9ec13256&generation=Generate
java.io.FileNotFoundException: E:sonarqube-6.7.1tempcnesreport75755325841492897151314598138129200\2020-03-06-ReportService-analysis-report.docx (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:146)
	at fr.cnes.sonar.report.factory.ReportFactory.report(ReportFactory.java:98)
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:133)
	at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:74)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:103)
	at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:86)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:72)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sancretor** [comment]
Hi @squall2751 !

Thank your for your feedback, we appreciate it !
I noticed you are using SonarQube on Windows, and we have known issues on this OS ...
This one seems to be related with a path : 

> java.io.FileNotFoundException: E:sonarqube-6.7.1tempcnesreport75755325841492897151314598138129200\2020-03-06-ReportService-analysis-report.docx (The system cannot find the path specified)

I can't say when we'll be able to have a look at those issues, as we mostly work on Linux platforms.  
But it seems to be a real bug on our side, sorry.

**Comment by minhnguyenvan95** [comment]
sonarqube in linux docker-compose 

`
sonarqube_1  | 2021.05.04 03:20:11 ERROR web[AXk1Y23Z/Sy4hyEQAAAU][o.s.s.w.WebServiceEngine] Fail to process request http://localhost:9000/api/cnesreport/report?key=project&branch=master&author=Administrator&token=xxxx&generation=Generate
sonarqube_1  | java.io.FileNotFoundException: /opt/sonarqube/temp/cnesreport1230167118313018368573640554877998/2021-05-04-project/project-analysis-report.docx (No such file or directory)
sonarqube_1  | 	at java.base/java.io.FileOutputStream.open0(Native Method)
sonarqube_1  | 	at java.base/java.io.FileOutputStream.open(Unknown Source)
sonarqube_1  | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
sonarqube_1  | 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
sonarqube_1  | 	at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:146)
sonarqube_1  | 	at fr.cnes.sonar.report.factory.ReportFactory.report(ReportFactory.java:99)
sonarqube_1  | 	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:137)
sonarqube_1  | 	at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:81)
sonarqube_1  | 	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
sonarqube_1  | 	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
sonarqube_1  | 	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
sonarqube_1  | 	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
sonarqube_1  | 	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
sonarqube_1  | 	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sonarqube_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
sonarqube_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
sonarqube_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
sonarqube_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
sonarqube_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
sonarqube_1  | 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
sonarqube_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
sonarqube_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
sonarqube_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
sonarqube_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
sonarqube_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
sonarqube_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
sonarqube_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
sonarqube_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
sonarqube_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
sonarqube_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
sonarqube_1  | 	at java.base/java.lang.Thread.run(Unknown Source)

`

**Comment by minhnguyenvan95** [comment]
Look like this line https://github.com/cnescatlab/sonar-cnes-report/blob/262c4caf469465e70a72265016e8e75a625c9b2d/src/main/java/fr/cnes/sonar/report/exporters/docx/DocXExporter.java#L146 didn't care about the folder creation so we could facing with java.io.FileNotFoundException

**Comment by minhnguyenvan95** [comment]
Instead of using cnes 3.2.2 which installed from marketplace , try to use sonar-cnes-report-3.3.1.jar and put it into /opt/sonarqube/extensions/plugins . It's worked for me .

**Comment by Sancretor** [comment]
Hi @minhnguyenvan95 

Thanks for your feedback !
The 3.3.1 version is now available from the Marketplace.
We will have a look at this line of code, as this error might occur again.

**Comment by Sancretor** [comment]
It seems like this issue was fixed.
We can't reproduce it on 3.3.1 and it works now for you too.
Don't hesitate to reopen it if it appears again !
