### ISSUE TITLE
NullPointerException on SonarQube 7.1

### ISSUE THREAD

**Issue by xduseko** [lequal/sonar-cnes-report#16]
I'm getting NPE when running against SonarQube 7.1. Is that a configuration problem or the plugin is only working with LTS Sonar? Thanks.

```
> java -jar sonar-cnes-report.jar --sonar.token d7d762b60aa6c40cfec4b42882cba7c68f836337 --sonar.url http://localhost:9000 --sonar.project.id cz.wincor.journal:UCMS --report.template ./template.docx --report.locale en_US

Exception in thread "main" java.lang.NullPointerException
        at fr.cnes.sonar.report.providers.LanguageProvider.getLanguage(LanguageProvider.java:67)
        at fr.cnes.sonar.report.providers.ProjectProvider.getProject(ProjectProvider.java:70)
        at fr.cnes.sonar.report.factory.ReportFactory.create(ReportFactory.java:96)
        at fr.cnes.sonar.report.ReportCommandLine.report(ReportCommandLine.java:185)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:149)
```

### Detection version
cnesreport 1.2.1

**Comment by begarco** [comment]
It doesn't seem to be a configuration problem.

cnesreport has not been tested on SonarQube 7 for now.

It may be caused by an API change in SonarQube 7.

**Comment by begarco** [comment]
@xduseko does it work now?

I did not manage to reproduce your error.

Which language are you analyzing?

Do you have some custom plugins installed?

**Comment by xduseko** [comment]
I don't think so unless you have changed anything. It was Java language, clean Sonar without additional plugins. Docker version with H2 database migrated into container.
