### ISSUE TITLE
NullPointerException in version 5.6.1

### ISSUE THREAD

**Issue by atedgimo** [lequal/sonar-cnes-report#29]
while running the project, I'm getting the following error:
Exception in thread "main" java.lang.NullPointerException
	at fr.cnes.sonar.report.model.Project.getQualityProfiles(Project.java:140)
	at fr.cnes.sonar.report.providers.ProjectProvider.getProject(ProjectProvider.java:69)
	at fr.cnes.sonar.report.factory.ReportFactory.create(ReportFactory.java:96)
	at fr.cnes.sonar.report.ReportCommandLine.report(ReportCommandLine.java:185)
	at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:149)

The following url is being invoked:
http://illin018:9000/api/navigation/component?componentKey=amdocs.att:cm-sonar:Att-1000

Output Json:
{"key":"amdocs.att:cm-sonar:Att-1000","uuid":"AVcYA0Y_5AdzXx0lNlJ0","name":"ABP:CM Att-1000","isComparable":true,"canBeFavorite":true,"isFavorite":true,"dashboards":[{"key":10003,"name":"Dashboard"},{"key":10004,"name":"Hotspots"},{"key":10005,"name":"Reviews"},{"key":10006,"name":"TimeMachine"},{"key":10940,"name":"Issues"},{"key":11160,"name":"Sqale"},{"key":11300,"name":"SCM Stats"},{"key":12300,"name":"Moti"}],"version":"1000-SNAPSHOT","snapshotDate":"2018-09-13T03:56:58+0300","extensions":[{"url":"/plugins/resource/amdocs.att%3Acm-sonar%3AAtt-1000?page=CsvExportPage","name":"CSV Export"}],"breadcrumbs":[{"key":"amdocs.att:cm-sonar:Att-1000","name":"ABP:CM Att-1000","qualifier":"TRK"}]}

looks like Quality Profile is not coming in the Json output, any idea?

**Comment by begarco** [comment]
Which version did you use?

Pre-build versions does not support SonarQube 5 versions.

If you want a compatible version you have to rebuild cnesreport from *master-for-lts-5* branch.

Otherwise you can wait for the release of cnesreport v2 which will contains LTS 5 support, but it is not for now.

**Comment by begarco** [comment]
@atedgimo is your problem solved?
