### ISSUE TITLE
[Enhancement] Adding support for private projects

### ISSUE THREAD

**Issue by LArmb** [lequal/sonar-cnes-report#7]
I think your tool can be very helpful, and I would like to use it in my SonarQube setup. Unfortunately, we have multiple users; and for security reasons, all projects are marked `private` and are only visible to specific users (usually only the project creator). Therefore, if an authorised user wants to generate reports with your tool, she needs to provide credentials that your tool can use to access the project. 
Currently, this is not possible, and your tool crashes, due to insufficient privileges:
```
Mar 26, 2018 6:09:22 PM fr.cnes.sonar.report.input.ParamsFactory create
INFO: Successfully processed parameters.
Mar 26, 2018 6:09:22 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: [WARN] Impossible to create the following directory: ./conf
Mar 26, 2018 6:09:23 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: Insufficient privileges
fr.cnes.sonar.report.exceptions.BadSonarQubeRequestException: Insufficient privileges
        at fr.cnes.sonar.report.providers.AbstractDataProvider.isErrorFree(AbstractDataProvider.java:261)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:294)
        at fr.cnes.sonar.report.providers.MeasureProvider.getMeasures(MeasureProvider.java:61)
        at fr.cnes.sonar.report.factory.ReportFactory.create(ReportFactory.java:82)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:138)

Mar 26, 2018 6:09:23 PM fr.cnes.sonar.report.ReportCommandLine main
INFO: Welcome to Sonar Report CNES
Here are the list of parameters you can use:
  > --sonar.url [mandatory]
  > --sonar.project.id [mandatory]
  > --report.author
  > --report.date
  > --report.path
  > --report.conf [yes|no]
  > --report.locale [fr_FR|en_US]
  > --report.template
  > --issues.template
Example :
java -jar sonar-report-cnes.jar --sonar.url http://sonarqube:9000 --sonar.project.id cat
```
As a quick fix, I tried to provide the credentials as part of the URL; i.e. instead of calling your tool with `http://example.com:9000`, I used `http://username:password@example.com:9000`. Unfortunately, that caused the same issue. (It works when accessing the SonarQube Web API with Linux's `curl`, but not with a browser or your tool.)

_I would be very grateful if you could add support for projects marked `private` by implementing an authentication process in your tool._

For testing purposes, I added some authentication in the `get` function of your `RequestManager`. At first glance, this seems to solve the problem, and no other classes are impacted. 
Unfortunately, this approach used credentials which were hard-coded. For proper usability, the credentials should be provided by the user as a parameter, and flowed down into the `RequestManager`. Thus, the impact of the change is less constricted, which is why I come to you here instead of fiddling around with your code myself.
For your convenience, I attach my version of the `RequestManager.java` with the hard-coded authentication. It is based on the first few hits that I got on google, so it might not be the most elegant solution ;-) It also has no error handling in case of invalid credentials, etc. But it might be a useful starting point for you.

[RequestManager_edited.zip](https://github.com/lequal/sonar-cnes-report/files/1848795/RequestManager_edited.zip)

**Comment by LArmb** [comment]
I see that you have not been working on this project for a short while (probably busy with other things). 
Do you already know if you will incorporate this feature? And if so, do you know when?
Thanks in advance!
