### ISSUE TITLE
Plugin: Wrong error code/message with invalid token

### ISSUE THREAD

**Issue by don-vip** [lequal/sonar-cnes-report#72]
### Expected behavior
When providing an invalid token to `api/cnesreport/report`, get a clear error message and forwards the HTTP 401 error code returned by SQ.

### Actual behavior
The plugin returns an HTTP error 500 with contents:
```json
{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
```
Stacktrace in logs:
```
2019.06.25 20:45:01 ERROR web[AWuP4sX2eXrRrvKpAAC+][o.s.s.w.WebServiceEngine] Fail to process request http://xxx/sonar/api/cnesreport/report?key=validkey&author=me&token=foo
fr.cnes.sonar.report.exceptions.BadSonarQubeRequestException: Unauthorized error sent by SonarQube server (code 401), please provide a valid authentication token to cnesreport.
        at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:133)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:321)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:275)
        at fr.cnes.sonar.report.providers.ProjectProvider.hasProject(ProjectProvider.java:107)
        at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:93)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:131)
        at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:74)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
        at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:88)
```
### Steps to reproduce behavior
- Install plugin 2.2.0
- Call API with an invalid token: http://xxx/sonar/api/cnesreport/report?key=validkey&author=me&token=foo

### Detection version
Plugin 2.2.0 with SonarQube 7.6.

**Comment by Sancretor** [comment]
Hi @don-vip !

Thanks for your feedback, we appreciate it.  
We will investigate on this soon, as it seems to be a bug.
