### ISSUE TITLE
Template fails to load

### ISSUE THREAD

**Issue by james-pardue** [lequal/sonar-cnes-report#8]
The issues-template.xlsx file fails to load when running on Windows 10 Pro or on Ubuntu 17.10.  Running sonar-cnes-report version 1.1.0.  The file is not corrupt, as it can be opened using Excel on Windows.

java -jar sonar-report-cnes.jar --sonar.url http://localhost:9000 --sonar.project.id myproject --report.template ./code-analysis-template.docx --report.template ./issues-template.xlsx
Jun 06, 2018 7:33:57 PM fr.cnes.sonar.report.input.ParamsFactory create
INFO: Successfully processed parameters.
Exception in thread "main" org.apache.poi.POIXMLException: org.apache.xmlbeans.XmlException: Element workbook@http://schemas.openxmlformats.org/spreadsheetml/2006/main is not a valid document@http://schemas.openxmlformats.org/wordprocessingml/2006/main document or a valid substitution.
        at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentRead(XWPFDocument.java:237)
        at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:169)
        at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:112)
        at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:124)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:165)
Caused by: org.apache.xmlbeans.XmlException: Element workbook@http://schemas.openxmlformats.org/spreadsheetml/2006/main is not a valid document@http://schemas.openxmlformats.org/wordprocessingml/2006/main document or a valid substitution.
        at org.apache.xmlbeans.impl.store.Locale.autoTypeDocument(Locale.java:322)
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1384)
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1363)
        at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:370)
        at org.apache.poi.POIXMLTypeLoader.parse(POIXMLTypeLoader.java:164)
        at org.openxmlformats.schemas.wordprocessingml.x2006.main.DocumentDocument$Factory.parse(Unknown Source)
        at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentRead(XWPFDocument.java:152)
        ... 4 more

**Comment by james-pardue** [comment]
Thanks @ohdinosaur everything is working perfectly with this adjustment!  Sorry if i missed this in the docs.

James
